# Generated by Django 4.2 on 2025-03-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('qualification', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
